### PR TITLE
Allow customized Vim mode prompt text on status bar

### PR DESCRIPTION
**Pull request by SPiCaRiA**
Everything mentioned in the ealier issue (#177) are implemented. Viola!

## CSS Class Names
| Mode    | Class Name                                                                 |
| ------- | -------------------------------------------------- |
| normal  | `plugin-obsidian-vimrc-support-prompt-normal`  |
| insert  | `plugin-obsidian-vimrc-support-prompt-insert`      |
| visual  | `plugin-obsidian-vimrc-support-prompt-visual`      |
| replace | `plugin-obsidian-vimrc-support-prompt-replace` |

## Demo
- **Settings Page**
Screen Shot 2023-03-27 at 15 54 23

- **Custom Text**
Screen Shot 2023-03-27 at 15 46 10

- **Status Bar**
Screen Shot 2023-03-27 at 14 46 27
Screen Shot 2023-03-27 at 14 47 06
Screen Shot 2023-03-27 at 14 47 15
Screen Shot 2023-03-27 at 14 47 23

- **Utilizing the CSS Classes**

Test with the CSS code below:

```css
.plugin-obsidian-vimrc-support-prompt-normal {
    color: red;
}
.plugin-obsidian-vimrc-support-prompt-insert {
    color: blue;
}
.plugin-obsidian-vimrc-support-prompt-visual {
    color: aqua;
}
.plugin-obsidian-vimrc-support-prompt-replace {
    color: green;
}
```

Screen Shot 2023-03-27 at 15 20 21
Screen Shot 2023-03-27 at 15 20 15
Screen Shot 2023-03-27 at 15 36 32
Screen Shot 2023-03-27 at 15 36 41

### CODE REVIEW

**Comment by SPiCaRiA** [comment]
Actually I'm thinking of also adding class names to the `div.status-bar`, which enables some powerline-ish styling. But not sure how people like it.

**Comment by SPiCaRiA** [comment]
New toggle option: Add Vim mode class to status bar

If the option is set to true, the corresponding CSS classes will also be added to the `div.status-bar` element. This allows custom CSS on the whole status bar such as some powerline-ish stylings.

### Demo
**Settings Page**
Screen Shot 2023-03-27 at 21 02 40

**Custom Status Bar**
Applying the one theme colors.

Screen Shot 2023-03-27 at 21 03 03
Screen Shot 2023-03-27 at 21 03 21
Screen Shot 2023-03-27 at 21 11 36
Screen Shot 2023-03-27 at 21 11 56

**Comment by SPiCaRiA** [comment]
One more show case with the powerline font and `:after` pseudo element :)

Screen Shot 2023-03-28 at 14 42 53
Screen Shot 2023-03-28 at 14 43 05
Screen Shot 2023-03-28 at 14 43 16
Screen Shot 2023-03-28 at 14 43 27

**Comment by esm7** [comment]
That's really cool, I'm sure many users would love it.
I'm sorry in advance that it might take me longer than it should to properly review and merge this, but it'll definitely get in!
One request I can already see that may be worthwhile: would you mind changing the usage of CSS classes (e.g. `plugin-obsidian-vimrc-support-prompt-normal`) to a class (e.g. `vimrc-support-vim-mode`) + a data attribute named `data-vim-mode`? I think it would make things cleaner.

**Comment by SPiCaRiA** [comment]
> That's really cool, I'm sure many users would love it. I'm sorry in advance that it might take me longer than it should to properly review and merge this, but it'll definitely get in! One request I can already see that may be worthwhile: would you mind changing the usage of CSS classes (e.g. `plugin-obsidian-vimrc-support-prompt-normal`) to a class (e.g. `vimrc-support-vim-mode`) + a data attribute named `data-vim-mode`? I think it would make things cleaner.

@esm7 Hi, sorry for the late response. I've just committed the changes, would you mind taking a look on it? Thank :D

**Comment by SPiCaRiA** [comment]
And the README updates, almost forgot about it :x

**Comment by SPiCaRiA** [comment]
I have figured out a problem that might be related with other parts of the plug-in. For details please check the issue I just posted #179

**Comment by esm7** [comment]
I want to add again that this is a really cool PR and I'm looking forward to getting it merged!

Two comments:
1. One more thing that I noticed when reviewing it, is that I'm unsure why the `vimModeStatusBarCSSClass` is actually needed. The whole-status-bar, Airline-style thing is really cool, but I believe that the extra setting is actually redundant. If I'm not mistaken, using the single data attribute in the internal element you can achieve the same thing by using the `::has` CSS selector. What do you think? If that's the case, I vote for keeping the code and the HTML elements as clean as possible and prevent the attribute duplication.
2. The Airline-like examples in this PR are too cool to be left here. I think they deserve a snippet and a screenshot in the documentation.

**Comment by SPiCaRiA** [comment]
> I want to add again that this is a really cool PR and I'm looking forward to getting it merged!
> 
> Two comments:
> 
> 1. One more thing that I noticed when reviewing it, is that I'm unsure why the `vimModeStatusBarCSSClass` is actually needed. The whole-status-bar, Airline-style thing is really cool, but I believe that the extra setting is actually redundant. If I'm not mistaken, using the single data attribute in the internal element you can achieve the same thing by using the `::has` CSS selector. What do you think? If that's the case, I vote for keeping the code and the HTML elements as clean as possible and prevent the attribute duplication.
> 2. The Airline-like examples in this PR are too cool to be left here. I think they deserve a snippet and a screenshot in the documentation.

1. Just did some research and you are right! I thought Obsidian does not support `has` selector (cuz it indeed didn't, a while ago), but it seems that in [v1.1.9](https://forum.obsidian.md/t/obsidian-release-v1-1-9/50426) they have upgraded the electron version so we shall be comforatble to remove the status bar CSS class. 😄 

2. Cool, definitely!

**Review by esm7 — APPROVED** [review]

**Comment by esm7** [comment]
>     1. Just did some research and you are right! I thought Obsidian does not support `has` selector (cuz it indeed didn't, a while ago), but it seems that in [v1.1.9](https://forum.obsidian.md/t/obsidian-release-v1-1-9/50426) they have upgraded the electron version so we shall be comforatble to remove the status bar CSS class. smile

I guess I was blessed by ignorance, as I tried `:has` for the first time in Obsidian just a couple of weeks ago, and never knew it was not supported at some point :laughing: 

Thanks again!

**Comment by SPiCaRiA** [comment]
@esm7 Big apologies, I just realized that I didn't remove the `console.log` line [here](<https://github.com/esm7/obsidian-vimrc-support/commit/d9dd46efd13845cd4e664e345a3b5d30c9334dcb#:~:text=console.log(this.plugin.settings.vimStatusPromptMap)%3B>) lol. Would you mind fixing that for me (so we don't need to go over the merge request red tapes)? Thanks!

**Comment by geblanco** [comment]
Hi how!

This looks reaaally fancy to have in Obsidian, any news on when will it make it to the next release?

Best,

**Pull request merged**
